### ISSUE TITLE
Splash screen for iOS

### ISSUE THREAD

**Issue by Okipa** [silviolleite/laravel-pwa#1]
Hi, 
First, thanks to your package !
Did you considered to add splash screen meta for iOS ? https://medium.com/@applification/progressive-web-app-splash-screens-80340b45d210

Quite simple to implement and great benefits !

**Comment by silviolleite** [comment]
Hello @Okipa  Thanks for this suggest! I'll include this soon.

**Comment by silviolleite** [comment]
Hello @Okipa It is Done! The splash screen meta for iOS was added in the new release 1.0.2.

**Comment by Okipa** [comment]
Thanks, will test this ;)

**Comment by shashankj99** [comment]
I've added my own splash-screen to the app... but it's still showing the default white screen with PWA icon... I've emptied cache and re-installed the app...
