### ISSUE TITLE
Laravel PWA: ServiceWorker registration failed:  DOMException

### ISSUE THREAD

**Issue by dugajean** [silviolleite/laravel-pwa#10]
Laravel: 5.8
PHP: 7.3

After a fresh install of this library on my Laravel app, I get the following error:

```
Laravel PWA: ServiceWorker registration failed:  DOMException
```

![image](https://user-images.githubusercontent.com/2448254/56912674-0c9e4c80-6ab0-11e9-835e-2d6f407021a2.png)

**Comment by dugajean** [comment]
Always work on the `localhost` domain or it wont work!

**Comment by EdrSantandr** [comment]
I just try it, with laravel 7 and I just change "/image/" to "image/" to make it work on localhost, but I tried to make it work on my local IP and access from my mobile, but I didn't work.
