### ISSUE TITLE
How to cache dynamic url?

### ISSUE THREAD

**Issue by CarolinaRatnaS** [silviolleite/laravel-pwa#11]
idk how to cache the dynamic url in serviceworker. How to cache them? Thanks!

**Comment by shigristudy** [comment]
replace you fetch listner with it, it will then cache the ajax requests as well

self.addEventListener('fetch', function(event) {
    event.respondWith(
      caches.match(event.request)
        .then(function(response) {
          if (response) {
            return response;     // if valid response is found in cache return it
          } else {
            return fetch(event.request)     //fetch from internet
              .then(function(res) {
                return caches.open(staticCacheName)
                  .then(function(cache) {
                    cache.put(event.request.url, res.clone());    //save the response for future
                    return res;   // return the fetched data
                  })
              })
              .catch(function(err) {       // fallback mechanism
                return caches.open(CACHE_CONTAINING_ERROR_MESSAGES)
                  .then(function(cache) {
                    return cache.match('offline');
                  });
              });
          }
        })
    );
  });

**Comment by fgilio** [comment]
Formatted:
```js
self.addEventListener("fetch", function (event) {
  event.respondWith(
  caches.match(event.request).then(function (response) {
    if (response) {
      return response;
      // if valid response is found in cache return it
    } else {
      return (
        fetch(event.request)
        //fetch from internet
        .then(function (res) {
          return caches.
          open(staticCacheName).
          then(function (cache) {
            cache.put(event.request.url, res.clone());
            //save the response for future
            return res;
            // return the fetched data
          });
        }).
        catch(function (err) {
          // fallback mechanism
          return caches.
          open(CACHE_CONTAINING_ERROR_MESSAGES).
          then(function (cache) {
            return cache.match("offline");
          });
        }));

    }
  }));

});
```

**Comment by CarolinaRatnaS** [comment]
Thank you!!!!! It's really works!! :""""D
