### ISSUE TITLE
Add to Home Button not showing in Chrome Dev tool

### ISSUE THREAD

**Issue by shigristudy** [silviolleite/laravel-pwa#12]
Add to home button is not showing in chrome Dev tool
![add to home](https://user-images.githubusercontent.com/26480545/59151494-9c3eff80-8a4d-11e9-86a2-631bac2e6acf.PNG)

**Comment by arkniazi** [comment]
I also couldn't find add to Home screen button. I followed the instructions as provided.

**Comment by arkniazi** [comment]
![Screenshot from 2019-06-10 18-57-10](https://user-images.githubusercontent.com/8684975/59200463-b42f9400-8bb1-11e9-95e6-7d0581b37df0.png)

Found the solution. You can install it through this.
Note: laravel is my project name

**Comment by silviolleite** [comment]
I am sorry, I've been busy lately. 
@arkniazi thanks for help.
