### ISSUE TITLE
@laravelPWA no run

### ISSUE THREAD

**Issue by mediaboost** [silviolleite/laravel-pwa#13]
Hello
@laravelPWA the blade directive no run ....

we can do another method to implement ?

**Comment by jerearaujo03** [comment]
Did you solve it?

**Comment by mediaboost** [comment]
Yes ...  i think a parse problem ...

**Comment by jerearaujo03** [comment]
I solved, it was cache problem.

**Comment by doug1n** [comment]
In my case, this package not work with Laravel-HTMLMin

**Comment by Erians** [comment]
Same problem with Laravel-HTMLMin

**Comment by idmahbub** [comment]
> Same problem with Laravel-HTMLMin



> In my case, this package not work with Laravel-HTMLMin

  yes I also experienced the same thing, any one solution?
