### ISSUE TITLE
cannot include new parameters in manifest.json

### ISSUE THREAD

**Issue by nachete1987** [silviolleite/laravel-pwa#2]
when I include new parameters in the laravelpwa.php file, these are not reflected in the manifest.json file generated

**Comment by silviolleite** [comment]
What parameters do you want to include over there?

**Comment by nachete1987** [comment]
In onesignal platform, I must include 2 new parameters in manifest.json and I cant do it

**Comment by silviolleite** [comment]
You can't do it yet, but I'll figure something out.

**Comment by nachete1987** [comment]
I'm also work in the resolution of this issue, thanks

**Comment by scottybo** [comment]
Any news on this? :)

**Comment by silviolleite** [comment]
Hello @scottybo and @nachete1987  It's Done ;) In the version 1.0.3 you can insert the custom tags in `manifest.json` editing the `config.php`. Further details on the `README.md`
