### ISSUE TITLE
@laravelPWA isn't displaying the header

### ISSUE THREAD

**Issue by maximeb97** [silviolleite/laravel-pwa#21]
Everything in the title. The @laravelPWA in the code isn't displaying the header.

Instead I used to temporary fix the problem
```
    @include('laravelpwa::meta', [
        'config' => (include('../config/laravelpwa.php'))["manifest"]
    ])
```

Did I missed something to make it works ?

**Comment by bitmatix** [comment]
Same here, it only works on some of our developer machines.

**Comment by bitmatix** [comment]
Resolved it byclearing the view cache:

`php artisan view:clear`
