### ISSUE TITLE
Larval Auth

### ISSUE THREAD

**Issue by matthewcocker** [silviolleite/laravel-pwa#26]
When a user signs in with Laravel Auth, I get the iOS webview after Auth is successful. If I tap done, it takes me to the login screen then throws a 419, but once I close the PWA and reopen it, it works as expected (the users Auth state remains signed in).

Do I have to add anything to stop this from happen?

**Comment by garrettboone** [comment]
Just a thought: Laravel 419 often has to do with missing csrf token.
