### ISSUE TITLE
How can i use laravelPWA without "php artisan serve" ?

### ISSUE THREAD

**Issue by hareprananda** [silviolleite/laravel-pwa#28]
When i run http://localhost/myapp/public ,it bring me error "Laravel PWA: ServiceWorker registration failed"

**Comment by TheFreeman15** [comment]
You need an HTTPS connection for PWA, if you are using xampp or laragon you can enable https in that

**Comment by hareprananda** [comment]
actually i can solve this problem by change the  the meta.blade.php  at the register part to http://localhost/your_project_name/public/serviceworker.js , and in the serviceworker.js add the full url to the filesToCache like this
const url="http://localhost/your_project_name/public";
var filesToCache = [
 url+"/offline",
url+"/css/app.css"
...
...
...
]
and also in the config/laravelpwa.php
add the full url to the icons and splash like the serviceworker.js above but using php language that use . instead + to concat the url
