### ISSUE TITLE
Popup for app install not showing up

### ISSUE THREAD

**Issue by goranculibrk** [silviolleite/laravel-pwa#3]
Hi there,
I have an issue with prompt to install the app. 
Right now, when I login to the app there is no popup to add to the home screen. I can do it by opening menu and clicking Add to home in Chrome. 
Is there a way to automatically show the prompt when user performs the login?
Thanks.

**Comment by silviolleite** [comment]
hello @goranculibrk, In order for a user to be able to install your Progressive Web App, it needs to meet the following criteria, you can see this link [https://developers.google.com/web/fundamentals/app-install-banners/](https://developers.google.com/web/fundamentals/app-install-banners/).
Sorry, lately I was busy.
