### ISSUE TITLE
Illegal string offset 'path'

### ISSUE THREAD

**Issue by odion-cloud** [silviolleite/laravel-pwa#33]
**Illegal string offset 'path'**
 hello i need help after successfully installed the latest update 
then i run @php artisan config:clear

when i open my url it shows this error
Illegal string offset 'path' (View: C:\xampp\htdocs\Churchaut\resources\views\layouts\index.blade.php) (View: C:\xampp\htdocs\Churchaut\resources\views\layouts\index.blade.php)

the project manisfect.json
'start_url' => asset(config('laravelpwa.manifest.start_url')),
            'display' => config('laravelpwa.manifest.display'),
            'theme_color' => config('laravelpwa.manifest.theme_color'),
            'background_color' => config('laravelpwa.manifest.background_color'),
            'orientation' =>  config('laravelpwa.manifest.orientation'),
            'status_bar' =>  config('laravelpwa.manifest.status_bar'),
            'splash' =>  config('laravelpwa.manifest.splash')
        ];
 
        foreach (config('laravelpwa.manifest.icons') as $size => $file) {
            $fileInfo = pathinfo($file['path']);
            $basicManifest['icons'][] = [
                'src' => $file['path'],
                'type' => 'image/' . $fileInfo['extension'],
                'sizes' => $size,
                'purpose' => $file['purpose']
            ];
        }
 
        foreach (config('laravelpwa.manifest.custom') as $tag => $value) {
             $basicManifest[$tag] = $value;
        }
        return $basicManifest;
    }
 
}

need help guys!!!!

**Comment by odion-cloud** [comment]
iss

**Comment by odion-cloud** [comment]
issue resolve

**Comment by vanimurarka** [comment]
How did the issue get resolved? I'm facing the same issue.
