### ISSUE TITLE
No manifest.json generated?

### ISSUE THREAD

**Issue by jmigdelacruz** [silviolleite/laravel-pwa#4]
Do we need to create a manifest.json file ourselves? It's not being detected by lighthouse too.

I thought the point of this was that the config/laravelpwa.php file would sort out the manifest.json file automatically.

**Comment by silviolleite** [comment]
Hello @jmigdelacruz, Did you Include within your `<head>` the blade directive `@laravelPWA`?

**Comment by jmigdelacruz** [comment]
Hi @silviolleite,  i've tried including `views/modules/laravelpwa/meta.blade.php.` However, it doesn't detect the `$config` variable and errors out.

Is there a missing route configuration step we missed in the readme? The blade partial contains `{{ route('laravelpwa.manifest') }}` but there was never any update to my routes file when i pulled your repo or am I missing something here?

Thanks for the response!

**Comment by silviolleite** [comment]
Ops! You must not include the template but just the directive `@laravelPWA` as bellow:

```html
<html>
<head>
    <title>My Title</title>
    ...
    @laravelPWA
</head>
<body>
    ...
    My content
    ...
</body>
</html>
```
Try again to follow the `README.md` spep by step.

**Comment by jmigdelacruz** [comment]
Ah, didn't know it was that simple to use 'blade directive.' Thanks @silviolleite. Great repo!

**Comment by jmigdelacruz** [comment]
btw @silviolleite, when i do @laravelPWA the blade directive isn't recognized and it just gets output as plain text.

do i need register this in AppServiceProvider.php?

**Comment by diegoferres** [comment]
> por cierto @silviolleite , cuando hago @laravelPWA, la directiva blade no se reconoce y solo se muestra como texto sin formato.
> 
> ¿Necesito registrar esto en AppServiceProvider.php?

Have you managed to solve?

**Comment by diegoferres** [comment]
> btw @silviolleite, when i do @laravelPWA the blade directive isn't recognized and it just gets output as plain text.
> 
> do i need register this in AppServiceProvider.php?

Have you managed to solve?

**Comment by ahmad-fauzan458** [comment]
I also have same problem

**Comment by omur00** [comment]
> Hi @silviolleite, i've tried including `views/modules/laravelpwa/meta.blade.php.` However, it doesn't detect the `$config` variable and errors out.
> 
> Is there a missing route configuration step we missed in the readme? The blade partial contains `{{ route('laravelpwa.manifest') }}` but there was never any update to my routes file, am I missing something here?
> 
> Thanks for the response!

If your @laravelPWA directive didn't work, just dump-autoload.

**Comment by BlueJ-D** [comment]
In case anybody finds this thread from google, as i did after getting routeNotFound exception. 
I needed to `php artisan cache:clear` then `php artisan route:cache` for the manifest.json to load. I guess this triggered the pwa added routes being generated.

This is not included as a step in readme
