### ISSUE TITLE
serviceworker.js:1 Uncaught (in promise) TypeError: Request failed

### ISSUE THREAD

**Issue by ezhevak** [silviolleite/laravel-pwa#43]
Hello i have the error:
Laravel PWA: ServiceWorker registration successful with scope:  https://divuar.com.ua/

serviceworker.js:1 Uncaught (in promise) TypeError: Request failed

var staticCacheName = "pwa-v" + new Date().getTime();
var filesToCache = [
    '/offline',
    '/css/app.css',
    '/js/app.js',
    '/images/icons/icon-72x72.png',
    '/images/icons/icon-96x96.png',
    '/images/icons/icon-128x128.png',
    '/images/icons/icon-144x144.png',
    '/images/icons/icon-152x152.png',
    '/images/icons/icon-192x192.png',
    '/images/icons/icon-384x384.png',
    '/images/icons/icon-512x512.png',
];

Please Explain me what the problem.
You can check site url https://divuar.com.ua

**Comment by mateus4k** [comment]
How did you solve this problem?

**Comment by ezhevak** [comment]
Сan't remember exactly.
But if I'm not mistaken, the list of files should be available.
In my example files were not available
'/css/app.css',
'/js/app.js',

**Comment by Jorzel21** [comment]
Saved my day!! Thanks a lot

**Comment by devingray** [comment]
For anybody else that is coming here for this issue. Ensure that `vendor/laravelpwa/offline.blade.php` is able to load at `/offline`
