### ISSUE TITLE
Undefined variable config in meta.blade.php file

### ISSUE THREAD

**Issue by SIMONNABUKO** [silviolleite/laravel-pwa#5]
I am getting this error when I include the meta.blade.php.
Or Am I including it in a wrong way? This is how I am doing it:
@include('modules.laravelpwa.meta') in my app.blade.php file. I get this error though
Undefined variable: config (View: C:\xampp\htdocs\queendom\resources\views\modules\laravelpwa\meta.blade.php) (View: C:\xampp\htdocs\queendom\resources\views\modules\laravelpwa\meta.blade.php) (View: C:\xampp\htdocs\queendom\resources\views\modules\laravelpwa\meta.blade.php)

**Comment by silviolleite** [comment]
hello @SIMONNABUKO, You must not include the template but just the directive `@laravelPWA` as bellow:

```html
<html>
<head>
    <title>My Title</title>
    ...
    @laravelPWA
</head>
<body>
    ...
    My content
    ...
</body>
</html>
```
