### ISSUE TITLE
Install option not showing Android google chrome

### ISSUE THREAD

**Issue by rksumon** [silviolleite/laravel-pwa#56]
I have heroku free host  its http not https. And not working but local server it works.

In my android install option not showing but only shortcut show.

Does pwa works http domain ?
Why my android shortcut show not install ?
( Note : my android from shortcut i can use most things except service worker )

Thank you.

**Comment by Umfi** [comment]
Service Workers need HTTPS to work.
See https://developers.google.com/web/fundamentals/primers/service-workers#you_need_https

**Comment by rksumon** [comment]
Thank you for your reply. Yes i upload my app into secure site, now it works.

But facing new problem, Cache do not save. My chrome dev toop under application/cache tab there is no cache save.

How do i solve this cache issue.

Thank you.
