### ISSUE TITLE
How can I remove the "Laravel" writing when opening the PWA from mobile

### ISSUE THREAD

**Issue by Silidrone** [silviolleite/laravel-pwa#59]
When opening the PWA from mobile after adding it on homescreen through Chrome, there is a screen before the app has been loaded, and it loads the logo I put in the laravelpwa.php and on the bottom it says "Laravel". How can I remove that Laravel writing?

![Screenshot_20210328-014021_Chrome](https://user-images.githubusercontent.com/17169590/112736849-e668dc00-8f66-11eb-8c7a-b51e6879e07b.jpg)

I put the screenshot as an attachment (I blurred out the logo and the top part of the phone), as you can see there is a "Laravel" writing on the bottom of the screen.

**Comment by leganz** [comment]
The name property is set in the config via env('APP_NAME')

**Comment by Silidrone** [comment]
Yes indeed, I figured it out a few minutes after posting this issue :D In any case, thanks.
