### ISSUE TITLE
Cache not refreshed using default serviceworker.js

### ISSUE THREAD

**Issue by jmigdelacruz** [silviolleite/laravel-pwa#8]
The page cache doesn't get updated when using default config.

My laravel app has cache-control headers defined but i guess the serviceworker takes precedence? I'm logging the `staticCacheName` variable and it can confirm it is updated correctly and outputs `pwa-v{{ timestamp of now() }}`. But still, it serves the cached version of the app weeks ago.

Any ideas @silviolleite ?

Actually, the serviceworker seems to give an error `Uncaught (in promise) TypeError: Request failed` the filesToCache only include images/icons.

**Comment by jmigdelacruz** [comment]
Ah actually, i found the issue. Seems like:

```
var filesToCache = [
   '/', <-------------------------------- THIS WAS CAUSING THE ISSUE. 
    '/images/icons/icon-72x72.png',
    '/images/icons/icon-96x96.png',
    '/images/icons/icon-128x128.png',
    '/images/icons/icon-144x144.png',
    '/images/icons/icon-152x152.png',
    '/images/icons/icon-192x192.png',
    '/images/icons/icon-384x384.png',
    '/images/icons/icon-512x512.png',
];
```
When i removed the line highlighted above, the cache was successfully refreshed. Could it be that the `'/'` route has some unsupported files that can't be cached?

**Comment by silviolleite** [comment]
Hello @jmigdelacruz try to use "." instead of "/" ... you can read more about in [https://developers.google.com/web/ilt/pwa/offline-quickstart](https://developers.google.com/web/ilt/pwa/offline-quickstart)
