### ISSUE TITLE
@Laravelpwa cannot be detected

### ISSUE THREAD

**Issue by Nab1l1000** [silviolleite/laravel-pwa#87]
I follow all the instruction from READ.md and one of it is inserting the @laravelpwa in the head tag.  The problems is, it doesn't detect and read the @laravelpwa in my coding. Can anyone help

**Comment by jdecode** [comment]
Did this work for you?
I am getting the same issue -`@laravelPWA` is added to the layout file, but there is no changes in the resultant/rendered HTML.

I have cleared cache/views (using `php artisan optimize:clear`)

I am running the app locally (so no HTTPS issue)
